# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temp_message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12temp_message.proto\"9\n\x04Temp\x12\x1d\n\ttemp_unit\x18\x01 \x01(\x0e\x32\n.Temp_Unit\x12\x12\n\ntemp_value\x18\x02 \x01(\x05*S\n\tTemp_Unit\x12\x19\n\x15TEMP_UNIT_UNSPECIFIED\x10\x00\x12\x14\n\x10TEMP_UNIT_KELVIN\x10\x01\x12\x15\n\x11TEMP_UNIT_CELSIUS\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'temp_message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_TEMP_UNIT']._serialized_start=81
  _globals['_TEMP_UNIT']._serialized_end=164
  _globals['_TEMP']._serialized_start=22
  _globals['_TEMP']._serialized_end=79
# @@protoc_insertion_point(module_scope)
