services:

    nodered:
        depends_on:
            - grafana
        image: nodered/node-red:latest
        environment:
            - TZ=Europe/Berlin
        ports:
            - "1880:1880"
        volumes:
            - nodered-data:/data
        network_mode: "host"

    influxdb:
        image: influxdb:latest
        ports:
            - '8086:8086'
        volumes:
            - influxdb2-data:/var/lib/influxdb2
            - influxdb2-config:/etc/influxdb2
        environment:
            DOCKER_INFLUXDB_INIT_MODE: setup
            DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/admin-username
            DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/admin-password
            DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/admin-token
            DOCKER_INFLUXDB_INIT_ORG: testorg
            DOCKER_INFLUXDB_INIT_BUCKET: testbucket
        secrets:
            - admin-username
            - admin-password
            - admin-token
        network_mode: "host"

    grafana:
        image: grafana/grafana:latest
        ports:
            - '3000:3000'
        volumes:
            - grafana-data:/var/lib/grafana
        depends_on:
            - influxdb
        environment:
            GF_SECURITY_ADMIN_USER__FILE: /run/secrets/admin-username
            GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/admin-password
        secrets:
            - admin-username
            - admin-password
        network_mode: "host"

secrets:
    admin-username:
        file: .env.admin-username
    admin-password:
        file: .env.admin-password
    admin-token:
        file: .env.admin-token

volumes:
    grafana-data:
    nodered-data:
    influxdb2-data:
    influxdb2-config:
    chronograf-data:
