# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor_message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14sensor_message.proto\"\x87\x01\n\x0cSensorStatus\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\n\n\x02id\x18\x02 \x01(\r\x12\x11\n\tsig_value\x18\x03 \x01(\x05\x12\x0e\n\x06\x66\x61\x63tor\x18\x04 \x01(\r\x12\x0e\n\x06offset\x18\x05 \x01(\r\x12%\n\x08sig_unit\x18\x06 \x01(\x0e\x32\x13.sensor_signal_unit\"K\n\x07\x43omJoin\x12\x0f\n\x07\x63onnect\x18\x01 \x01(\r\x12\x1a\n\x04type\x18\x02 \x01(\x0e\x32\x0c.sensor_type\x12\x13\n\x0bsample_freq\x18\x03 \x01(\r\" \n\x0b\x43omJoinResp\x12\x11\n\tsensor_id\x18\x01 \x01(\r*\x93\x01\n\x12sensor_signal_unit\x12\x14\n\x10UNIT_UNSPECIFIED\x10\x00\x12\x14\n\x10UNIT_TEMP_KELVIN\x10\x01\x12\x15\n\x11UNIT_TEMP_CELSIUS\x10\x02\x12\x11\n\rUNIT_PRES_BAR\x10\x03\x12\x14\n\x10UNIT_PRES_PASCAL\x10\x04\x12\x11\n\rUNIT_ROTA_RPM\x10\x05*I\n\x0bsensor_type\x12\x14\n\x10TYPE_TEMPERATURE\x10\x00\x12\x11\n\rTYPE_PRESSURE\x10\x01\x12\x11\n\rTYPE_ROTATION\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SENSOR_SIGNAL_UNIT']._serialized_start=274
  _globals['_SENSOR_SIGNAL_UNIT']._serialized_end=421
  _globals['_SENSOR_TYPE']._serialized_start=423
  _globals['_SENSOR_TYPE']._serialized_end=496
  _globals['_SENSORSTATUS']._serialized_start=25
  _globals['_SENSORSTATUS']._serialized_end=160
  _globals['_COMJOIN']._serialized_start=162
  _globals['_COMJOIN']._serialized_end=237
  _globals['_COMJOINRESP']._serialized_start=239
  _globals['_COMJOINRESP']._serialized_end=271
# @@protoc_insertion_point(module_scope)
