# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: system_message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14system_message.proto\"\xa7\x01\n\x04RDBI\x12\x17\n\x02id\x18\x01 \x01(\x0e\x32\x0b.request_id\x12\x0f\n\x07value_0\x18\x02 \x01(\r\x12\x0f\n\x07value_1\x18\x03 \x01(\r\x12\x0f\n\x07value_2\x18\x04 \x01(\r\x12\x0f\n\x07value_3\x18\x05 \x01(\r\x12\x0f\n\x07value_4\x18\x06 \x01(\r\x12\x0f\n\x07value_5\x18\x07 \x01(\r\x12\x0f\n\x07value_6\x18\x08 \x01(\r\x12\x0f\n\x07value_7\x18\t \x01(\r\"\xac\x01\n\tRDBI_resp\x12\x17\n\x02id\x18\x01 \x01(\x0e\x32\x0b.request_id\x12\x0f\n\x07value_0\x18\x02 \x01(\r\x12\x0f\n\x07value_1\x18\x03 \x01(\r\x12\x0f\n\x07value_2\x18\x04 \x01(\r\x12\x0f\n\x07value_3\x18\x05 \x01(\r\x12\x0f\n\x07value_4\x18\x06 \x01(\r\x12\x0f\n\x07value_5\x18\x07 \x01(\r\x12\x0f\n\x07value_6\x18\x08 \x01(\r\x12\x0f\n\x07value_7\x18\t \x01(\r*g\n\nrequest_id\x12\x14\n\x10GET_SENSOR_COUNT\x10\x00\x12\x17\n\x13GET_ALERT_THRESHOLD\x10\x01\x12\x17\n\x13SET_ALERT_THRESHOLD\x10\x02\x12\x11\n\rDISPLAY_GRAPH\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'system_message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_REQUEST_ID']._serialized_start=369
  _globals['_REQUEST_ID']._serialized_end=472
  _globals['_RDBI']._serialized_start=25
  _globals['_RDBI']._serialized_end=192
  _globals['_RDBI_RESP']._serialized_start=195
  _globals['_RDBI_RESP']._serialized_end=367
# @@protoc_insertion_point(module_scope)
